### ISSUE TITLE
incorrect padding

### ISSUE THREAD

**Issue by hugosvirak** [SemjonEschweiler/metro-art#12]
![image](https://github.com/SemjonEschweiler/metro-art/assets/50474584/2b1a8c8f-16db-4b74-a870-859ddbe772f9)

**Comment by hugosvirak** [comment]
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Source\HugoSvirak\metro-art\processor\app.py", line 16, in process_image
    openCvImage = base64ToNp("/9j/4TTkRXhpZgAASUkqAAgAAAAKABIBAwABAAAABgAAABMCAwABAAAAAQAAABoBBQABAAAAhgAAABsBBQABAAAAjgAAACgBAwABAAAAAgAAAA8BAgAIAAAAlgAAABABAgAJAAAAngAAADEBAgAOAAAApwAAADIBAgAUAAAAtQAAAGmHBAABAAAAyQAAAG4DAABIAAAAAQAAAEgAAAABAAAAc2Ftc3VuZwBTTS1BNTM2QgBBNTM2QlhYVTZDV0U5ADIwMjM6MDc6MzAgMDk6Mjc6NDAAJwCaggUAAQAAAKMCAACdggUAAQAAAKsCAAAiiAMAAQAAAAIAAAAniAMAAQAAALgAAAAAkAcABAAAADAyMjADkAIAFAAAALMCAAAEkAIAFAAAAMcCAAAQkAIABwAAANsCAAARkAIABwAAAOICAAASkAIABwAAAOkCAAABkgoAAQAAAPACAAACkgUAAQAAAPgCAAADkgoAAQAAAAADAAAEkgoAAQAAAAgDAAAFkgUAAQAAABADAAAHkgMAAQAAAAIAAAAJkgMAAQAAAAAAAAAAoAcABAAAADAxMDABkQcABAAAAAECAwAKkgUAAQAAABgDAACQkgIABQAAACADAACRkgIABQAAACUDAACSkgIABQAAACoDAACGkgcADQAAAC8DAAABoAMAAQAAAAEAAAACoAQAAQAAANACAAADoAQAAQAAAOABAAABowcABAAAAAEAAAABpAMAAQAAAAAAAAACpAMAAQAAAAAAAAADpAMAAQAAAAAAAAAEpAUAAQAAADwDAAAFpAMAAQAAABgAAAAGpAMAAQAAAAAAAAAIpAMAAQAAAAAAAAAJpAMAAQAAAAAAAAAKpAMAAQAAAAAAAAAgpAIADAAAAEQDAAAFoAQAAQAAAFADAAAAAAAAAQAAADIAAAC0AAAAZAAAADIwMjM6MDc6MzAgMDk6Mjc6NDAAMjAyMzowNzozMCAwOToyNzo0MAArMDI6MDAAKzAyOjAwACswMjowMAA0AgA")
  File "C:\Source\HugoSvirak\metro-art\processor\app.py", line 11, in base64ToNp
    nparr = numpy.frombuffer(base64.b64decode(imageAsBase64), numpy.uint8)
  File "C:\Users\hluccarini\AppData\Local\Programs\Python\Python310\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by hugosvirak** [comment]
Press CTRL+C to quit
127.0.0.1 - - [30/Jul/2023 11:10:45] "POST /process HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "c:\Source\HugoSvirak\metro-art\processor\.venv\lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "c:\Source\HugoSvirak\metro-art\processor\.venv\lib\site-packages\werkzeug\serving.py", line 325, in execute
    application_iter = app(environ, start_response)
  File "c:\Source\HugoSvirak\metro-art\processor\.venv\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Source\HugoSvirak\metro-art\processor\.venv\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "c:\Source\HugoSvirak\metro-art\processor\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Source\HugoSvirak\metro-art\processor\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Source\HugoSvirak\metro-art\processor\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Source\HugoSvirak\metro-art\processor\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Source\HugoSvirak\metro-art\processor\app.py", line 18, in process_image
    cv2.imwrite("test.png", openCvImage)
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:787: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
